```{r}
library(ggplot2)
library(dplyr)
library(here)
charts.data <- read.csv(here("demoTesting", "copper-data-for-tutorial.csv"))

# View the updated dataset
head(charts.data)
```

```{r}
head(area_vs_height_data)
```

```{r}
# with fill component
p2 <- ggplot() + geom_area(aes(y = export, x = year, fill=product), data = charts.data,
                           stat="identity")
p2
```


```{r}
# without fill component
#CRP: This is what you had:
p2 <- ggplot() + geom_area(aes(y = export, x = year), data = charts.data,
                           stat="identity")
p2
```



```{r}
# without fill component
#CRP: This is my suggestion. Since you only have a single category to plot, just subsample the dataset to one of the levels in product and plot it. You effectively have a single mountain per plot.
charts.data_sub <- charts.data[charts.data$product == "copper",]
head(charts.data_sub)
#Here's the plot
p3 <- ggplot() + geom_area(aes(y = export, x = year), data = charts.data_sub,
                           stat="identity")
p3
```


## Area vs Height Dataset

```{r}

area_vs_height_data <- read.csv(here("demoTesting", "height_vs_area_data_for_city_Aalborg.csv"))


#You'll have to add all the areas at a given height before
#plotting the data.
length(unique(area_vs_height_data$height))
length(unique(area_vs_height_data$area))

p <- ggplot(area_vs_height_data[1:200,]) + 
    geom_area(aes(y = area, x = height)) +
    theme_minimal()
  
p

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```